module.exports = codes = {
    FIREBASE_VERIFICATION_ERROR_CODE:2001,

    ADD_TO_CART_SUCCESS:3001,
    ADD_TO_CART_FAILED:3002,
    REMOVE_FROM_CART_SUCCESS:3003,
    REMOVE_FROM_CART_FAILED:3004,
    GET_CART_ITEMS_SUCCESS:3005,
    GET_CART_ITEMS_FAILED:3006,



}